#!/usr/bin/env ruby
require 'rubygems'
require 'nokogiri'
require 'rest-client'
require 'rexml/document'

# Parameters
url = 'http://upload.wikimedia.org/wikipedia/commons/5/55/Blank_map_world_gmt_%28more_simplified%29.svg'
svg_path   = File.join(File.dirname(__FILE__), 'world-map.svg')
style_path = File.join(File.dirname(__FILE__), 'style.css')
indent = 2

# Download
puts "Downloading from #{url} ..."
doc = Nokogiri::XML(RestClient.get(url))

# Insert description and style
desc = doc.create_element('desc', "World map generated by Color my Map (https://github.com/freayd/color-my-map)")
style = doc.create_element('style', :type => 'text/css')
style.add_child(doc.create_cdata(File.open(style_path).read))
doc.at_css('svg').children.first.add_previous_sibling(style).add_previous_sibling(desc)

# Insert country IDs
doc.at_css('path[d^="M1888.686,566.202l0.119-0.24l-0.119-0.121h-0.24l-0.12-0.12v-0.24"]')['id'] = 'mongolia'

# Write
puts "Writing to #{svg_path} ..."
File.open(svg_path, 'w') do |file|
    doc = REXML::Document.new(doc.to_xml, :attribute_quote => :quote)
    doc.write(file, indent)
end

# REXML bugfix: replace single quotes by double ones in <xml> element
doc = File.open(svg_path).read
doc.gsub!(/^<\?xml version='(\d+\.?\d*)' encoding='([\w\-]+)'\?>/, '<?xml version="\1" encoding="\2"?>')
File.open(svg_path, 'w') { |file| file << doc }
