svg:
    url:
        - http://commons.wikimedia.org/wiki/Category:Blank_SVG_maps_of_the_world
        - http://commons.wikimedia.org/wiki/File:Blank_map_world_gmt_%28more_simplified%29.svg
        - http://upload.wikimedia.org/wikipedia/commons/5/55/Blank_map_world_gmt_%28more_simplified%29.svg
    path:   world-map.svg
    indent: 2
style:
    path: style.css
attributes:
    # Translate IDs from german to english
    'g#Hintergrund':     id.set(background)
    'g#Staaten_1_':      id.set(countries)
    'g#Seen':            id.set(seas)
    'g#Binneninseln_1_': id.set(inland-island)
    'g#Flüsse_groß':     id.set(big-rivers)
    'g#Staatengrenzen':  id.set(country-borders)
    'g#Gradnetz':        id.set(coordinates)
    'g#Staatennamen':    id.set(country-names)
    'g#Rahmen':          id.set(frame)
    # Remove hard coded style attributes
    'g#background rect[fill="#D0E5F2"]': id.set(main-water);fill.remove()
    'g#countries path[fill="#FFF2DF"][stroke="#008CDF"][stroke-width="0.05"]':     fill.remove();stroke.remove();stroke-width.remove()
    'g#seas path[fill="#D0E5F2"][stroke="#008CDF"][stroke-width="0.05"]':          fill.remove();stroke.remove();stroke-width.remove()
    'g#inland-island path[fill="#FFF2DF"][stroke="#008CDF"][stroke-width="0.05"]': fill.remove();stroke.remove();stroke-width.remove()
    'g#big-rivers path[fill="none"][stroke="#0064DF"][stroke-width="0.1"][stroke-linecap="round"][stroke-linejoin="round"][stroke-miterlimit="10"]':     fill.remove();stroke.remove();stroke-width.remove();stroke-linecap.remove();stroke-linejoin.remove();stroke-miterlimit.remove()
    'g#big-rivers line[fill="none"][stroke="#0064DF"][stroke-width="0.1"][stroke-linecap="round"][stroke-linejoin="round"][stroke-miterlimit="10"]':     fill.remove();stroke.remove();stroke-width.remove();stroke-linecap.remove();stroke-linejoin.remove();stroke-miterlimit.remove()
    'g#big-rivers polyline[fill="none"][stroke="#0064DF"][stroke-width="0.1"][stroke-linecap="round"][stroke-linejoin="round"][stroke-miterlimit="10"]': fill.remove();stroke.remove();stroke-width.remove();stroke-linecap.remove();stroke-linejoin.remove();stroke-miterlimit.remove()
    'g#coordinates line[fill="none"][stroke="#A3A3A3"][stroke-width="0.15"][stroke-linecap="round"][stroke-linejoin="round"][stroke-miterlimit="10"]':      fill.remove();stroke.remove();stroke-width.remove();stroke-linecap.remove();stroke-linejoin.remove();stroke-miterlimit.remove()
    'g#coordinates polyline [fill="none"][stroke="#A3A3A3"][stroke-width="0.15"][stroke-linecap="round"][stroke-linejoin="round"][stroke-miterlimit="10"]': fill.remove();stroke.remove();stroke-width.remove();stroke-linecap.remove();stroke-linejoin.remove();stroke-miterlimit.remove()
    'g#country-names text[font-family="''Myriad-Roman''"][font-size="3"]':  class.add(name);font-family.remove();font-size.remove()
    'g#country-names tspan[font-family="''Myriad-Roman''"][font-size="3"]': class.add(name);font-family.remove();font-size.remove()
    'g#frame text[font-family="''ArialMT''"][font-size="13"]': font-family.remove();font-size.remove()
    # Identify countries
    'path[d^="M2101.205,1071.043l0.12-0.121h-0.36"]':                              id.set(australia)
    'path[d^="M1694.285,743.681l0.12-0.12v-0.119h-0.12v-0.24"]':                   id.set(india)
    'path[d^="M1888.686,566.202l0.119-0.24l-0.119-0.121h-0.24l-0.12-0.12v-0.24"]': id.set(mongolia)
    'path[d^="M1642.925,689.202l-0.12-0.24l-0.119,0.12v0.12l-0.24,0.12h0.119"]':   id.set(nepal)
    'path[d^="M2195.525,1181.801v0.121h-0.12l-0.12,0.121h-0.12l-0.24,0.119"]':     id.set(south-island);class.add(new-zealand)
    'path[d^="M2228.405,1115.322v0.119h-0.24v0.121h0.12v0.119h-0.12l0.12,0.119"]': id.set(north-island);class.add(new-zealand)