svg:
    url:    http://upload.wikimedia.org/wikipedia/commons/5/55/Blank_map_world_gmt_%28more_simplified%29.svg
    path:   world-map.svg
    indent: 2
style:
    path: style.css
attributes:
    'path[d^="M2101.205,1071.043l0.12-0.121h-0.36"]':                              id.set(australia)
    'path[d^="M1694.285,743.681l0.12-0.12v-0.119h-0.12v-0.24"]':                   id.set(india)
    'path[d^="M1888.686,566.202l0.119-0.24l-0.119-0.121h-0.24l-0.12-0.12v-0.24"]': id.set(mongolia)
    'path[d^="M1642.925,689.202l-0.12-0.24l-0.119,0.12v0.12l-0.24,0.12h0.119"]':   id.set(nepal)
    'path[d^="M2195.525,1181.801v0.121h-0.12l-0.12,0.121h-0.12l-0.24,0.119"]':     id.set(new-zealand)
    '[fill="#FFF2DF"][stroke="#008CDF"][stroke-width="0.05"]': class.add(ground);fill.remove();stroke.remove();stroke-width.remove()
